<?php
/*
 * StashAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace StashAPILib;

use StashAPILib\Controllers;

/**
 * StashAPILib client class
 */
class StashAPIClient
{
 
    /**
     * Singleton access to API controller
     * @return Controllers\APIController The *Singleton* instance
     */
    public function getClient()
    {
        return Controllers\APIController::getInstance();
    }
}
