<?php
/**
 * AdminApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stash API
 *
 * REST-ish endpoint for interacting with Stash
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdminApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addGroupToUser
     *
     * addGroupToUser.
     *
     */
    public function testAddGroupToUser()
    {

    }

    /**
     * Test case for addUserToGroup
     *
     * addUserToGroup.
     *
     */
    public function testAddUserToGroup()
    {

    }

    /**
     * Test case for addUserToGroups
     *
     * addUserToGroups.
     *
     */
    public function testAddUserToGroups()
    {

    }

    /**
     * Test case for addUsersToGroup
     *
     * addUsersToGroup.
     *
     */
    public function testAddUsersToGroup()
    {

    }

    /**
     * Test case for clearSenderAddress
     *
     * clearSenderAddress.
     *
     */
    public function testClearSenderAddress()
    {

    }

    /**
     * Test case for clearUserCaptchaChallenge
     *
     * clearUserCaptchaChallenge.
     *
     */
    public function testClearUserCaptchaChallenge()
    {

    }

    /**
     * Test case for createGroup
     *
     * createGroup.
     *
     */
    public function testCreateGroup()
    {

    }

    /**
     * Test case for createUser
     *
     * createUser.
     *
     */
    public function testCreateUser()
    {

    }

    /**
     * Test case for deleteGroup
     *
     * deleteGroup.
     *
     */
    public function testDeleteGroup()
    {

    }

    /**
     * Test case for deleteMailConfig
     *
     * deleteMailConfig.
     *
     */
    public function testDeleteMailConfig()
    {

    }

    /**
     * Test case for deleteUser
     *
     * deleteUser.
     *
     */
    public function testDeleteUser()
    {

    }

    /**
     * Test case for findGroupsForUser
     *
     * findGroupsForUser.
     *
     */
    public function testFindGroupsForUser()
    {

    }

    /**
     * Test case for findOtherGroupsForUser
     *
     * findOtherGroupsForUser.
     *
     */
    public function testFindOtherGroupsForUser()
    {

    }

    /**
     * Test case for findUsersInGroup
     *
     * findUsersInGroup.
     *
     */
    public function testFindUsersInGroup()
    {

    }

    /**
     * Test case for findUsersNotInGroup
     *
     * findUsersNotInGroup.
     *
     */
    public function testFindUsersNotInGroup()
    {

    }

    /**
     * Test case for getClusterInformation
     *
     * getClusterInformation.
     *
     */
    public function testGetClusterInformation()
    {

    }

    /**
     * Test case for getGroups1
     *
     * getGroups.
     *
     */
    public function testGetGroups1()
    {

    }

    /**
     * Test case for getGroupsWithAnyPermission
     *
     * getGroupsWithAnyPermission.
     *
     */
    public function testGetGroupsWithAnyPermission()
    {

    }

    /**
     * Test case for getGroupsWithoutAnyPermission
     *
     * getGroupsWithoutAnyPermission.
     *
     */
    public function testGetGroupsWithoutAnyPermission()
    {

    }

    /**
     * Test case for getLicense
     *
     * getLicense.
     *
     */
    public function testGetLicense()
    {

    }

    /**
     * Test case for getMailConfig
     *
     * getMailConfig.
     *
     */
    public function testGetMailConfig()
    {

    }

    /**
     * Test case for getSenderAddress
     *
     * getSenderAddress.
     *
     */
    public function testGetSenderAddress()
    {

    }

    /**
     * Test case for getUsers
     *
     * getUsers.
     *
     */
    public function testGetUsers()
    {

    }

    /**
     * Test case for getUsersWithAnyPermission
     *
     * getUsersWithAnyPermission.
     *
     */
    public function testGetUsersWithAnyPermission()
    {

    }

    /**
     * Test case for getUsersWithoutAnyPermission
     *
     * getUsersWithoutAnyPermission.
     *
     */
    public function testGetUsersWithoutAnyPermission()
    {

    }

    /**
     * Test case for removeGroupFromUser
     *
     * removeGroupFromUser.
     *
     */
    public function testRemoveGroupFromUser()
    {

    }

    /**
     * Test case for removeUserFromGroup
     *
     * removeUserFromGroup.
     *
     */
    public function testRemoveUserFromGroup()
    {

    }

    /**
     * Test case for renameUser
     *
     * renameUser.
     *
     */
    public function testRenameUser()
    {

    }

    /**
     * Test case for revokePermissionsForGroup
     *
     * revokePermissionsForGroup.
     *
     */
    public function testRevokePermissionsForGroup()
    {

    }

    /**
     * Test case for revokePermissionsForUser
     *
     * revokePermissionsForUser.
     *
     */
    public function testRevokePermissionsForUser()
    {

    }

    /**
     * Test case for setMailConfig
     *
     * setMailConfig.
     *
     */
    public function testSetMailConfig()
    {

    }

    /**
     * Test case for setPermissionForGroups
     *
     * setPermissionForGroups.
     *
     */
    public function testSetPermissionForGroups()
    {

    }

    /**
     * Test case for setPermissionForUsers
     *
     * setPermissionForUsers.
     *
     */
    public function testSetPermissionForUsers()
    {

    }

    /**
     * Test case for setSenderAddress
     *
     * setSenderAddress.
     *
     */
    public function testSetSenderAddress()
    {

    }

    /**
     * Test case for updateLicense
     *
     * updateLicense.
     *
     */
    public function testUpdateLicense()
    {

    }

    /**
     * Test case for updateUserDetails
     *
     * updateUserDetails.
     *
     */
    public function testUpdateUserDetails()
    {

    }

    /**
     * Test case for updateUserPassword
     *
     * updateUserPassword.
     *
     */
    public function testUpdateUserPassword()
    {

    }

}
