<?php
/**
 * ProjectApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stash API
 *
 * REST-ish endpoint for interacting with Stash
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ProjectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createProject
     *
     * createProject.
     *
     */
    public function testCreateProject()
    {

    }

    /**
     * Test case for deleteProject
     *
     * deleteProject.
     *
     */
    public function testDeleteProject()
    {

    }

    /**
     * Test case for getProject
     *
     * getProject.
     *
     */
    public function testGetProject()
    {

    }

    /**
     * Test case for getProjectAvatar
     *
     * getProjectAvatar.
     *
     */
    public function testGetProjectAvatar()
    {

    }

    /**
     * Test case for getProjectGroupsWithAnyPermission
     *
     * getProjectGroupsWithAnyPermission.
     *
     */
    public function testGetProjectGroupsWithAnyPermission()
    {

    }

    /**
     * Test case for getProjectGroupsWithoutAnyPermission
     *
     * getProjectGroupsWithoutAnyPermission.
     *
     */
    public function testGetProjectGroupsWithoutAnyPermission()
    {

    }

    /**
     * Test case for getProjectUsersWithAnyPermission
     *
     * getProjectUsersWithAnyPermission.
     *
     */
    public function testGetProjectUsersWithAnyPermission()
    {

    }

    /**
     * Test case for getProjectUsersWithoutPermission
     *
     * getProjectUsersWithoutPermission.
     *
     */
    public function testGetProjectUsersWithoutPermission()
    {

    }

    /**
     * Test case for getProjects
     *
     * getProjects.
     *
     */
    public function testGetProjects()
    {

    }

    /**
     * Test case for hasProjectAllUserPermission
     *
     * hasProjectAllUserPermission.
     *
     */
    public function testHasProjectAllUserPermission()
    {

    }

    /**
     * Test case for modifyProjectAllUserPermission
     *
     * modifyProjectAllUserPermission.
     *
     */
    public function testModifyProjectAllUserPermission()
    {

    }

    /**
     * Test case for revokeProjectPermissionsForGroup
     *
     * revokeProjectPermissionsForGroup.
     *
     */
    public function testRevokeProjectPermissionsForGroup()
    {

    }

    /**
     * Test case for revokeProjectPermissionsForUser
     *
     * revokeProjectPermissionsForUser.
     *
     */
    public function testRevokeProjectPermissionsForUser()
    {

    }

    /**
     * Test case for setProjectPermissionForGroups
     *
     * setProjectPermissionForGroups.
     *
     */
    public function testSetProjectPermissionForGroups()
    {

    }

    /**
     * Test case for setProjectPermissionForUsers
     *
     * setProjectPermissionForUsers.
     *
     */
    public function testSetProjectPermissionForUsers()
    {

    }

    /**
     * Test case for updateProject
     *
     * updateProject.
     *
     */
    public function testUpdateProject()
    {

    }

    /**
     * Test case for uploadProjectAvatar
     *
     * uploadProjectAvatar.
     *
     */
    public function testUploadProjectAvatar()
    {

    }

}
