<?php
/**
 * PullRequestApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stash API
 *
 * REST-ish endpoint for interacting with Stash
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PullRequestApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PullRequestApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for approvePullRequest
     *
     * approvePullRequest.
     *
     */
    public function testApprovePullRequest()
    {

    }

    /**
     * Test case for assignPullRequestParticipantRole
     *
     * assignPullRequestParticipantRole.
     *
     */
    public function testAssignPullRequestParticipantRole()
    {

    }

    /**
     * Test case for canMergePullRequest
     *
     * canMergePullRequest.
     *
     */
    public function testCanMergePullRequest()
    {

    }

    /**
     * Test case for countPullRequestTasks
     *
     * countPullRequestTasks.
     *
     */
    public function testCountPullRequestTasks()
    {

    }

    /**
     * Test case for createPullRequest
     *
     * createPullRequest.
     *
     */
    public function testCreatePullRequest()
    {

    }

    /**
     * Test case for createPullRequestComment
     *
     * createPullRequestComment.
     *
     */
    public function testCreatePullRequestComment()
    {

    }

    /**
     * Test case for declinePullRequest
     *
     * declinePullRequest.
     *
     */
    public function testDeclinePullRequest()
    {

    }

    /**
     * Test case for deletePullRequestComment
     *
     * deletePullRequestComment.
     *
     */
    public function testDeletePullRequestComment()
    {

    }

    /**
     * Test case for getPullRequest
     *
     * getPullRequest.
     *
     */
    public function testGetPullRequest()
    {

    }

    /**
     * Test case for getPullRequestActivities
     *
     * getPullRequestActivities.
     *
     */
    public function testGetPullRequestActivities()
    {

    }

    /**
     * Test case for getPullRequestChanges
     *
     * getPullRequestChanges.
     *
     */
    public function testGetPullRequestChanges()
    {

    }

    /**
     * Test case for getPullRequestComment
     *
     * getPullRequestComment.
     *
     */
    public function testGetPullRequestComment()
    {

    }

    /**
     * Test case for getPullRequestComments
     *
     * getPullRequestComments.
     *
     */
    public function testGetPullRequestComments()
    {

    }

    /**
     * Test case for getPullRequestCommits
     *
     * getPullRequestCommits.
     *
     */
    public function testGetPullRequestCommits()
    {

    }

    /**
     * Test case for getPullRequestDiff
     *
     * getPullRequestDiff.
     *
     */
    public function testGetPullRequestDiff()
    {

    }

    /**
     * Test case for getPullRequestDiffByPath
     *
     * getPullRequestDiffByPath.
     *
     */
    public function testGetPullRequestDiffByPath()
    {

    }

    /**
     * Test case for getPullRequestTasks
     *
     * getPullRequestTasks.
     *
     */
    public function testGetPullRequestTasks()
    {

    }

    /**
     * Test case for getPullRequests
     *
     * getPullRequests.
     *
     */
    public function testGetPullRequests()
    {

    }

    /**
     * Test case for listPullRequestParticipants
     *
     * listPullRequestParticipants.
     *
     */
    public function testListPullRequestParticipants()
    {

    }

    /**
     * Test case for mergePullRequest
     *
     * mergePullRequest.
     *
     */
    public function testMergePullRequest()
    {

    }

    /**
     * Test case for reopenPullRequest
     *
     * reopenPullRequest.
     *
     */
    public function testReopenPullRequest()
    {

    }

    /**
     * Test case for unassignPullRequestParticipantRole
     *
     * unassignPullRequestParticipantRole.
     *
     */
    public function testUnassignPullRequestParticipantRole()
    {

    }

    /**
     * Test case for unwatchPullRequest
     *
     * unwatchPullRequest.
     *
     */
    public function testUnwatchPullRequest()
    {

    }

    /**
     * Test case for updatePullRequest
     *
     * updatePullRequest.
     *
     */
    public function testUpdatePullRequest()
    {

    }

    /**
     * Test case for updatePullRequestComment
     *
     * updatePullRequestComment.
     *
     */
    public function testUpdatePullRequestComment()
    {

    }

    /**
     * Test case for watchPullRequest
     *
     * watchPullRequest.
     *
     */
    public function testWatchPullRequest()
    {

    }

    /**
     * Test case for withdrawPullRequestApproval
     *
     * withdrawPullRequestApproval.
     *
     */
    public function testWithdrawPullRequestApproval()
    {

    }

}
