<?php
/**
 * RepositoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Stash API
 *
 * REST-ish endpoint for interacting with Stash
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RepositoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RepositoryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createRepository
     *
     * createRepository.
     *
     */
    public function testCreateRepository()
    {

    }

    /**
     * Test case for createRepositoryCommitComment
     *
     * createRepositoryCommitComment.
     *
     */
    public function testCreateRepositoryCommitComment()
    {

    }

    /**
     * Test case for deleteRepository
     *
     * deleteRepository.
     *
     */
    public function testDeleteRepository()
    {

    }

    /**
     * Test case for deleteRepositoryCommitComment
     *
     * deleteRepositoryCommitComment.
     *
     */
    public function testDeleteRepositoryCommitComment()
    {

    }

    /**
     * Test case for disableRepositoryHook
     *
     * disableRepositoryHook.
     *
     */
    public function testDisableRepositoryHook()
    {

    }

    /**
     * Test case for enableRepositoryHook
     *
     * enableRepositoryHook.
     *
     */
    public function testEnableRepositoryHook()
    {

    }

    /**
     * Test case for forkRepository
     *
     * forkRepository.
     *
     */
    public function testForkRepository()
    {

    }

    /**
     * Test case for getForkedRepositories
     *
     * getForkedRepositories.
     *
     */
    public function testGetForkedRepositories()
    {

    }

    /**
     * Test case for getRelatedRepositories
     *
     * getRelatedRepositories.
     *
     */
    public function testGetRelatedRepositories()
    {

    }

    /**
     * Test case for getRepositories
     *
     * getRepositories.
     *
     */
    public function testGetRepositories()
    {

    }

    /**
     * Test case for getRepositories1
     *
     * getRepositories.
     *
     */
    public function testGetRepositories1()
    {

    }

    /**
     * Test case for getRepository
     *
     * getRepository.
     *
     */
    public function testGetRepository()
    {

    }

    /**
     * Test case for getRepositoryBranches
     *
     * getRepositoryBranches.
     *
     */
    public function testGetRepositoryBranches()
    {

    }

    /**
     * Test case for getRepositoryChanges
     *
     * getRepositoryChanges.
     *
     */
    public function testGetRepositoryChanges()
    {

    }

    /**
     * Test case for getRepositoryCommit
     *
     * getRepositoryCommit.
     *
     */
    public function testGetRepositoryCommit()
    {

    }

    /**
     * Test case for getRepositoryCommitChanges
     *
     * getRepositoryCommitChanges.
     *
     */
    public function testGetRepositoryCommitChanges()
    {

    }

    /**
     * Test case for getRepositoryCommitComment
     *
     * getRepositoryCommitComment.
     *
     */
    public function testGetRepositoryCommitComment()
    {

    }

    /**
     * Test case for getRepositoryCommitComments
     *
     * getRepositoryCommitComments.
     *
     */
    public function testGetRepositoryCommitComments()
    {

    }

    /**
     * Test case for getRepositoryCommitDiff
     *
     * getRepositoryCommitDiff.
     *
     */
    public function testGetRepositoryCommitDiff()
    {

    }

    /**
     * Test case for getRepositoryCommitDiffByPath
     *
     * getRepositoryCommitDiffByPath.
     *
     */
    public function testGetRepositoryCommitDiffByPath()
    {

    }

    /**
     * Test case for getRepositoryCommits
     *
     * getRepositoryCommits.
     *
     */
    public function testGetRepositoryCommits()
    {

    }

    /**
     * Test case for getRepositoryContent
     *
     * getRepositoryContent.
     *
     */
    public function testGetRepositoryContent()
    {

    }

    /**
     * Test case for getRepositoryContentByPath
     *
     * getRepositoryContentByPath.
     *
     */
    public function testGetRepositoryContentByPath()
    {

    }

    /**
     * Test case for getRepositoryDefaultBranch
     *
     * getRepositoryDefaultBranch.
     *
     */
    public function testGetRepositoryDefaultBranch()
    {

    }

    /**
     * Test case for getRepositoryGroupsWithAnyPermission
     *
     * getRepositoryGroupsWithAnyPermission.
     *
     */
    public function testGetRepositoryGroupsWithAnyPermission()
    {

    }

    /**
     * Test case for getRepositoryGroupsWithoutAnyPermission
     *
     * getRepositoryGroupsWithoutAnyPermission.
     *
     */
    public function testGetRepositoryGroupsWithoutAnyPermission()
    {

    }

    /**
     * Test case for getRepositoryHook
     *
     * getRepositoryHook.
     *
     */
    public function testGetRepositoryHook()
    {

    }

    /**
     * Test case for getRepositoryHookSettings
     *
     * getRepositoryHookSettings.
     *
     */
    public function testGetRepositoryHookSettings()
    {

    }

    /**
     * Test case for getRepositoryHooks
     *
     * getRepositoryHooks.
     *
     */
    public function testGetRepositoryHooks()
    {

    }

    /**
     * Test case for getRepositoryTags
     *
     * getRepositoryTags.
     *
     */
    public function testGetRepositoryTags()
    {

    }

    /**
     * Test case for getRepositoryUsersWithAnyPermission
     *
     * getRepositoryUsersWithAnyPermission.
     *
     */
    public function testGetRepositoryUsersWithAnyPermission()
    {

    }

    /**
     * Test case for getRepositoryUsersWithoutPermission
     *
     * getRepositoryUsersWithoutPermission.
     *
     */
    public function testGetRepositoryUsersWithoutPermission()
    {

    }

    /**
     * Test case for listRepositoryFiles
     *
     * listRepositoryFiles.
     *
     */
    public function testListRepositoryFiles()
    {

    }

    /**
     * Test case for listRepositoryFilesByPath
     *
     * listRepositoryFilesByPath.
     *
     */
    public function testListRepositoryFilesByPath()
    {

    }

    /**
     * Test case for repositoryCompareChanges
     *
     * repositoryCompareChanges.
     *
     */
    public function testRepositoryCompareChanges()
    {

    }

    /**
     * Test case for repositoryCompareCommits
     *
     * repositoryCompareCommits.
     *
     */
    public function testRepositoryCompareCommits()
    {

    }

    /**
     * Test case for repositoryCompareDiffByPath
     *
     * repositoryCompareDiffByPath.
     *
     */
    public function testRepositoryCompareDiffByPath()
    {

    }

    /**
     * Test case for repositoryShowDiff
     *
     * repositoryShowDiff.
     *
     */
    public function testRepositoryShowDiff()
    {

    }

    /**
     * Test case for repositoryShowDiffByPath
     *
     * repositoryShowDiffByPath.
     *
     */
    public function testRepositoryShowDiffByPath()
    {

    }

    /**
     * Test case for retryCreateRepository
     *
     * retryCreateRepository.
     *
     */
    public function testRetryCreateRepository()
    {

    }

    /**
     * Test case for revokeRepositoryPermissionsForGroup
     *
     * revokeRepositoryPermissionsForGroup.
     *
     */
    public function testRevokeRepositoryPermissionsForGroup()
    {

    }

    /**
     * Test case for revokeRepositoryPermissionsForUser
     *
     * revokeRepositoryPermissionsForUser.
     *
     */
    public function testRevokeRepositoryPermissionsForUser()
    {

    }

    /**
     * Test case for setRepositoryDefaultBranch
     *
     * setRepositoryDefaultBranch.
     *
     */
    public function testSetRepositoryDefaultBranch()
    {

    }

    /**
     * Test case for setRepositoryHookSettings
     *
     * setRepositoryHookSettings.
     *
     */
    public function testSetRepositoryHookSettings()
    {

    }

    /**
     * Test case for setRepositoryPermissionForGroup
     *
     * setRepositoryPermissionForGroup.
     *
     */
    public function testSetRepositoryPermissionForGroup()
    {

    }

    /**
     * Test case for setRepositoryPermissionForUser
     *
     * setRepositoryPermissionForUser.
     *
     */
    public function testSetRepositoryPermissionForUser()
    {

    }

    /**
     * Test case for unwatchRepositoryCommit
     *
     * unwatchRepositoryCommit.
     *
     */
    public function testUnwatchRepositoryCommit()
    {

    }

    /**
     * Test case for updateRepository
     *
     * updateRepository.
     *
     */
    public function testUpdateRepository()
    {

    }

    /**
     * Test case for updateRepositoryCommitComment
     *
     * updateRepositoryCommitComment.
     *
     */
    public function testUpdateRepositoryCommitComment()
    {

    }

    /**
     * Test case for watchRepositoryCommit
     *
     * watchRepositoryCommit.
     *
     */
    public function testWatchRepositoryCommit()
    {

    }

}
